<a href="https://colab.research.google.com/github/Viswanth13/PDS_Asg2_Viswanth/blob/main/src/Assignment2_PDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 2

In [42]:
# importing pandas and dataset file

In [43]:
import pandas as pd

df = pd.read_csv('./raw/As2_train.csv')

df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13 km/kg,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50

a) Look for the missing values in all the columns and either impute them (replace with mean, median, or mode) or drop them. Justify your action for this task.

In [44]:
# check what columns have missing values and count of them.

In [45]:
print(df.isnull().sum())

print(df.dtypes)

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  38
New_Price            5032
Price                   0
dtype: int64
Unnamed: 0             int64
Name                  object
Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage               object
Engine                object
Power                 object
Seats                float64
New_Price             object
Price                float64
dtype: object

b) Remove the units from some of the attributes and only keep the numerical values (for
example remove kmpl from “Mileage”, CC from “Engine”, bhp from “Power”, and lakh from
“New_price”).

In [46]:
df['Mileage'] = df['Mileage'].str.replace(r'\s+[a-zA-Z/]+', '', regex=True)
df['Engine'] = df['Engine'].str.replace(r'\s+CC', '', regex=True)
df['Power'] = df['Power'].str.replace(r'\s+bhp', '', regex=True)
df['New_Price'] = df['New_Price'].str.replace(r'\s+Lakh', '', regex=True)

df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582,126.2,5.0,NaN,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13,1199,88.7,5.0,8.61,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248,88.76,7.0,NaN,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2,1968,140.8,5.0,NaN,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08,1461,63.1,5.0,NaN,3.50

In [47]:
# replace the missing values in Mileage, Engine, Power and Seats columns

In [48]:
df['Mileage'].fillna(df['Mileage'].median(),inplace=True)
df['Engine'].fillna(df['Engine'].median(),inplace=True)
df['Power'].fillna(df['Power'].median(),inplace=True)

df['Seats'].fillna(df['Seats'].mode()[0],inplace=True)

In [49]:
# dropping the 'New_Price' column since there are lot of missing values

In [50]:
df.drop('New_Price', axis=1, inplace=True)

In [51]:
print(df.isnull().sum())

Unnamed: 0           0
Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
Price                0
dtype: int64

c) Change the categorical variables (“Fuel_Type” and “Transmission”) into numerical one hot
encoded value.

In [52]:
fuel_mapping = {'Diesel': 0, 'Petrol': 1, 'Electric': 2}
df['Fuel_Type'] = df['Fuel_Type'].replace(fuel_mapping)

transmission_mapping = {'Manual': 0, 'Automatic': 1}
df['Transmission'] = df['Transmission'].replace(transmission_mapping)

df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582,126.2,5.0,12.50
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13,1199,88.7,5.0,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248,88.76,7.0,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.2,1968,140.8,5.0,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461,63.1,5.0,3.50

In [53]:
# getting current year to calculate age of the car

In [54]:
from datetime import datetime

current_year = datetime.now().year

d) Create one more feature and add this column to the dataset (you can use mutate function in
R for this). For example, you can calculate the current age of the car by subtracting “Year” value
from the current year.

In [55]:
df['Age_of_Car'] = current_year - df['Year']

In [56]:
df['Power_per_Liter'] = (df['Power'].astype(float) / df['Mileage'].astype(float)).round(2)

In [57]:
df['Mileage_per_Seat'] = (df['Mileage'].astype(float) / df['Seats'].astype(float)).round(2)

In [58]:
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Age_of_Car,Power_per_Liter,Mileage_per_Seat
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582,126.2,5.0,12.50,9,6.42,3.93
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13,1199,88.7,5.0,4.50,13,6.82,2.60
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248,88.76,7.0,6.00,12,4.27,2.97
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.2,1968,140.8,5.0,17.74,11,9.26,3.04
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461,63.1,5.0,3.50,11,2.73,4.62

In [59]:
preprocessed_csv_file = './results/preprocessed_data.csv'
df.to_csv(preprocessed_csv_file, index=False)

e) Perform select, filter, rename, mutate, arrange and summarize with group by operations (or
their equivalent operations in python) on this dataset.

Selecting columns

In [60]:
# selecting columns

In [61]:
required_columns = ['Name', 'Mileage', 'Engine', 'Seats']
df_selected = df[required_columns]
df_selected.head()

                               Name Mileage Engine  Seats
0  Hyundai Creta 1.6 CRDi SX Option   19.67   1582    5.0
1                      Honda Jazz V      13   1199    5.0
2                 Maruti Ertiga VDI   20.77   1248    7.0
3   Audi A4 New 2.0 TDI Multitronic    15.2   1968    5.0
4            Nissan Micra Diesel XV   23.08   1461    5.0

In [62]:
selected_csv_file = './results/selected_data.csv'
df_selected.to_csv(selected_csv_file, index=False)

Filter Statement

In [63]:
# filtering rows based on conditions

In [64]:
filtered_df = df[(df['Mileage'].astype(float) > 20) & (df['Engine'].astype(float) < 1500)]
filtered_df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Age_of_Car,Power_per_Liter,Mileage_per_Seat
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248,88.76,7.0,6.00,12,4.27,2.97
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461,63.1,5.0,3.50,11,2.73,4.62
7,9,Tata Indica Vista Quadrajet LS,Chennai,2012,65932,0,0,Second,22.3,1248,74,5.0,1.95,12,3.32,4.46
8,10,Maruti Ciaz Zeta,Kochi,2018,25692,1,0,First,21.56,1462,103.25,5.0,9.95,6,4.79,4.31
10,12,Maruti Swift VDI BSIV,Jaipur,2015,64424,0,0,First,25.2,1248,74,5.0,5.60,9,2.94,5.04

In [65]:
filtered_csv_file = './results/filtered_data.csv'
filtered_df.to_csv(filtered_csv_file, index=False)

Rename function

In [66]:
# renaming column

In [67]:
renamed_df = df.rename(columns={'Power_per_Liter': 'Power_per_Fuel'})
renamed_df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Age_of_Car,Power_per_Fuel,Mileage_per_Seat
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582,126.2,5.0,12.50,9,6.42,3.93
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13,1199,88.7,5.0,4.50,13,6.82,2.60
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248,88.76,7.0,6.00,12,4.27,2.97
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.2,1968,140.8,5.0,17.74,11,9.26,3.04
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461,63.1,5.0,3.50,11,2.73,4.62

Arrange

In [68]:
# sorting the df based on age of the car and Mileage features

In [69]:
sorted_df = df.sort_values(by=['Age_of_Car', 'Mileage'], ascending=[True, False])
sorted_df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Age_of_Car,Power_per_Liter,Mileage_per_Seat
4198,4328,Maruti Swift DDiS VDI,Coimbatore,2019,41075,0,0,First,28.4,1248,74,5.0,8.40,5,2.61,5.68
984,1018,Maruti Swift Dzire VDI Optional,Kochi,2019,18592,0,0,First,26.59,1248,74,5.0,8.51,5,2.78,5.32
4267,4399,Maruti Swift Dzire AMT ZDI,Chennai,2019,65000,0,1,First,26.59,1248,74,5.0,6.75,5,2.78,5.32
5405,5560,Renault KWID RXT Optional,Kochi,2019,6568,1,0,First,25.17,799,53.3,5.0,5.09,5,2.12,5.03
5628,5789,Renault KWID RXL,Kochi,2019,7858,1,0,First,25.17,799,53.3,5.0,3.80,5,2.12,5.03

In [70]:
arranged_csv_file = './results/arranged_data.csv'
sorted_df.to_csv(arranged_csv_file, index=False)

In [71]:
df['Mileage'] = df['Mileage'].astype(float)

Transform function

In [72]:
# To know the mean mileage based on location

In [73]:
df['Avg_Mileage_Location'] = df.groupby('Location')['Mileage'].transform('mean')
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price,Age_of_Car,Power_per_Liter,Mileage_per_Seat,Avg_Mileage_Location
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,0,0,First,19.67,1582,126.2,5.0,12.50,9,6.42,3.93,17.886576
1,2,Honda Jazz V,Chennai,2011,46000,1,0,First,13.00,1199,88.7,5.0,4.50,13,6.82,2.60,18.236576
2,3,Maruti Ertiga VDI,Chennai,2012,87000,0,0,First,20.77,1248,88.76,7.0,6.00,12,4.27,2.97,18.236576
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,0,1,Second,15.20,1968,140.8,5.0,17.74,11,9.26,3.04,17.844200
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,0,0,First,23.08,1461,63.1,5.0,3.50,11,2.73,4.62,19.189777

In [74]:
transformed_csv_file = './results/transformed_data.csv'
df.to_csv(transformed_csv_file, index=False)

Summarize

In [75]:
# Getting the mean mileage based on fuel type

In [76]:
grouped_df = df.groupby('Fuel_Type').agg({'Mileage': 'mean'}).sort_values(by='Mileage', ascending=False)
grouped_df.head()

             Mileage
Fuel_Type
0          18.652661
2          18.190000
1          17.576509

In [77]:
summary_csv_file = './results/summary_data.csv'
grouped_df.to_csv(summary_csv_file, index=False)